### ISSUE TITLE
android crash if sharedPreferencesName not supplied 

### ISSUE THREAD

**Issue by npomfret** [classapp/react-native-sensitive-info#18]
I'll submit a PR shortly.

```
Exception in native call
                                                             com.facebook.react.bridge.NoSuchKeyException: couldn't find key sharedPreferencesName in dynamic object
                                                                 at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
                                                                 at br.com.classapp.RNSensitiveInfo.RNSensitiveInfoModule.getItem(RNSensitiveInfoModule.java:26)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                                 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
```

**Comment by npomfret** [comment]
What state is this project in, is it still being maintained?  I tried to submit a PR but then noticed that there have been a bunch of unreleased commits since the npm version (4.0.0). My fix doesn't really apply to master.

**Comment by ricardofavero** [comment]
Thank you for working on this issue. The problem with the unreleased commits was solved. Right now we are busy with other projects, but you're welcome to open a pull request.

**Comment by npomfret** [comment]
@ricardofavero here you go https://github.com/classapp/react-native-sensitive-info/pull/22

I was a bit confused by the `initKeyStore` stuff that's appeared in there.  It doesn't seem to be used, but also broke my build - i couldn't even compile.  I've backed out a build file change that was causing the problem as a part of this PR, but there seems to be quite a bit of stuff in there still that isn't used (and maybe is [partially reverted](https://github.com/classapp/react-native-sensitive-info/commit/3cd62798947b567c7ee85c4d4212131c01ce3e05)??).
